name: client
version: 0.1.0.0
license: MIT
author: "Yaroslava Khrabrova"
maintainer: "yaroslava.khrabrova.etu@univ-lille.fr"
category: Networking
extra-source-files: []

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - text
  - websockets
  - HUnit
  - hspec

library:
  source-dirs: app
  exposed-modules:
    - Client
    - MessageValidator
    - Automaton

executables:
  client:
    main: Main.hs
    source-dirs: app
    dependencies:
      - client

tests:
  client-test:
    main: TestMain.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - hspec
      - HUnit
      - client